name: CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check-types:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-yarn
      - run: yarn type-check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-yarn
      - run: yarn lint

  test:
    name: Unit tests (Vitest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-yarn
      - run: yarn test:coverage

  build:
    name: Build
    needs:
      - check-types
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-yarn
      - run: yarn build
